modLoader="javafml"
loaderVersion="[36,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="rechanic"
version="1.2.5"
displayName="ReChanic"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="http://discord.laurinhummel.de"
authors="SkyExit"

[[dependencies.rechanic]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




